app:
  name: svc
  image:
    repository: "onecx/onecx-product-store-svc"
  db:
    enabled: true
  operator:
    microservice:
      spec:
        description: OneCX Product Store Backend Service
        name: OneCX Product Store SVC
