---
openapi: 3.0.3
info:
  title: onecx-product-store mfe operator service
  version: 1.0.0
servers:
  - url: "http://onecx-product-store:8080"
tags:
  - name: operatorMfe
paths:
  /operator/mfe/v1/{productName}/{appId}:
    put:
      security:
        - oauth2: [ ocx-ps-mfe:write ]
      tags:
        - operatorMfe
      description: Creates or updates a product micro-frontend.
      operationId: createOrUpdateMfe
      parameters:
        - name: productName
          in: path
          description: product name
          required: true
          schema:
            type: string
        - name: appId
          in: path
          description: App ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMfeRequest'
      responses:
        "201":
          description: Create new micro-frontend
        "204":
          description: Update existing micro-frontend
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-ps-mfe:write: Grants write access
  schemas:
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    UpdateMfeRequest:
      required:
        - remoteEntry
        - exposedModule
        - appName
        - remoteBaseUrl
      type: object
      properties:
        remoteName:
          type: string
        tagName:
          type: string
        appVersion:
          type: string
        appName:
          type: string
        description:
          type: string
        remoteBaseUrl:
          type: string
        remoteEntry:
          type: string
        classifications:
          type: array
          uniqueItems: true
          items:
            type: string
        contact:
          type: string
        iconName:
          type: string
        note:
          type: string
        exposedModule:
          type: string
        technology:
          type: string
        type:
          $ref: "#/components/schemas/MicrofrontendType"
        deprecated:
          type: boolean
        undeployed:
          type: boolean
        endpoints:
          type: array
          items:
            $ref: "#/components/schemas/UpdateMfeUIEndpointRequest"
        hasParameter:
          type: boolean
    UpdateMfeUIEndpointRequest:
      required:
        - path
        - name
      type: object
      properties:
        path:
          type: string
        name:
          type: string
    MicrofrontendType:
      type: string
      enum: [ MODULE, COMPONENT ]






