---
openapi: 3.0.3
info:
  title: onecx-product-store mfe operator service
  version: 1.0.0
servers:
  - url: "http://onecx-product-store:8080"
tags:
  - name: operatorMfe
paths:
  /operator/mfe/v1/{mfeId}:
     put:
      tags:
        - operatorMfe
      description: Creates or updates a product micro-frontend.
      operationId: createOrUpdateMfe
      parameters:
        - name: mfeId
          in: path
          description: Mfe ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMfeRequest'
      responses:
        "201":
          description: Create new micro-frontend
        "204":
          description: Update existing micro-frontend
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
components:
  schemas:
    RestException:
       type: object
       properties:
         errorCode:
           type: string
         message:
           type: string
         parameters:
           type: array
           items:
             type: object
         namedParameters:
           type: object
           additionalProperties:
             type: object
         validations:
           type: array
           items:
             $ref: '#/components/schemas/ValidationConstraint'
    ValidationConstraint:
      type: object
      properties:
        parameter:
          type: string
        message:
          type: string
    UpdateMfeRequest:
      required:
        - remoteEntry
        - remoteName
        - exposedModule
        - displayName
        - moduleType
        - remoteBaseUrl
        - productName
      type: object
      properties:
        productName:
          minLength: 2
          type: string
        remoteEntry:
          minLength: 2
          type: string
        remoteName:
          minLength: 2
          type: string
        exposedModule:
          minLength: 2
          type: string
        displayName:
          minLength: 2
          type: string
        moduleType:
          $ref: '#/components/schemas/ModuleType'
        wcTagName:
          type: string
        appId:
          type: string
        appVersion:
          type: string
        note:
          type: string
        contact:
          type: string
        remoteBaseUrl:
          minLength: 2
          type: string
    ModuleType:
      enum:
        - ANGULAR
        - WEBCOMPONENT
      type: string
