---
openapi: 3.0.3
info:
  title: onecx-product-store slot operator service
  description: This API provides endpoints for the onecx-product-store-operator to manage Slots
  version: 1.0.0
servers:
  - url: "http://onecx-product-store-svc:8080"
tags:
  - name: operatorSlot
    description: Managing Slots
paths:
  /operator/slot/v1/{productName}/{appId}:
    put:
      security:
        - oauth2: [ ocx-ps-slot:write ]
      tags:
        - operatorSlot
      description: Creates or updates a slot of a product by the product name and an appId of a microfrontend
      operationId: createOrUpdateSlot
      parameters:
        - name: productName
          in: path
          description: product name
          required: true
          schema:
            type: string
        - name: appId
          in: path
          description: App ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSlotRequest'
      responses:
        "201":
          description: Slot created successfully
        "204":
          description: Slot updated successfully
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-ps-slot:write: Grants write access
  schemas:
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    UpdateSlotRequest:
      type: object
      required:
        - name
      properties:
        description:
          type: string
        name:
          type: string
        undeployed:
          type: boolean
        deprecated:
          type: boolean