---
openapi: 3.0.3
info:
  title: onecx-product-store product operator service
  version: 1.0.0
servers:
  - url: "http://onecx-product-store:8080"
tags:
  - name: operatorProduct
paths:
  /operator/product/v1/update/{name}:
    put:
      security:
        - oauth2: [ ocx-ps-product:write ]
      tags:
        - operatorProduct
      description: Creates or updates a product registration.
      operationId: createOrUpdateProduct
      parameters:
        - name: name
          in: path
          description: Product name
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductRequest'
      responses:
        "201":
          description: Create new product
        "204":
          description: Update existing product
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-ps-product:write: Grants write access
  schemas:
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    UpdateProductRequest:
      required:
        - basePath
        - version
      type: object
      properties:
        version:
          type: string
        description:
          type: string
        imageUrl:
          type: string
        basePath:
          type: string
        displayName:
          type: string
        iconName:
          type: string
        classifications:
          type: array
          uniqueItems: true
          items:
            type: string
        undeployed:
          type: boolean
        provider:
          type: string
        multitenancy:
          type: boolean