---
openapi: 3.0.3
info:
  title: onecx-product-store mfe operator service
  version: 1.0.0
servers:
  - url: "http://onecx-product-store:8080"
tags:
  - name: operatorMfe
paths:
  /operator/mfe/v1/{appId}:
    put:
      tags:
        - operatorMfe
      description: Creates or updates a product micro-frontend.
      operationId: createOrUpdateMfe
      parameters:
        - name: appId
          in: path
          description: App ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMfeRequest'
      responses:
        "201":
          description: Create new micro-frontend
        "204":
          description: Update existing micro-frontend
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  schemas:
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    UpdateMfeRequest:
      required:
        - remoteEntry
        - exposedModule
        - appName
        - remoteBaseUrl
        - productName
      type: object
      properties:
        remoteName:
          type: string
        tagName:
          type: string
        appVersion:
          type: string
        appName:
          type: string
        description:
          type: string
        remoteBaseUrl:
          type: string
        remoteEntry:
          type: string
        productName:
          type: string
        classifications:
          type: array
          uniqueItems: true
          items:
            type: string
        contact:
          type: string
        iconName:
          type: string
        note:
          type: string
        exposedModule:
          type: string
        technology:
          type: string
        endpoints:
          type: array
          items:
            $ref: "#/components/schemas/UpdateMfeUIEndpointRequest"
    UpdateMfeUIEndpointRequest:
      required:
        - path
        - name
      type: object
      properties:
        path:
          type: string
        name:
          type: string







