---
openapi: 3.0.3
info:
  title: onecx-product-store ms operator service
  version: 1.0.0
servers:
  - url: "http://onecx-product-store:8080"
tags:
  - name: operatorMs
paths:
  /operator/ms/v1/{productName}/{appId}:
    put:
      security:
        - oauth2: [ ocx-ps-ms:write ]
      tags:
        - operatorMs
      description: Creates or updates a product micro-service.
      operationId: createOrUpdateMs
      parameters:
        - name: productName
          in: path
          description: product name
          required: true
          schema:
            type: string
        - name: appId
          in: path
          description: App ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMsRequest'
      responses:
        "201":
          description: Create new micro-service
        "204":
          description: Update existing micro-service
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-ps-ms:write: Grants write access
  schemas:
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    UpdateMsRequest:
      type: object
      properties:
        version:
          type: string
        description:
          type: string
        name:
          type: string
        type:
          type: string
        undeployed:
          type: boolean
